name: Check JJB templates

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install virtualenv
        run: pip3 install virtualenv
      - name: Test JJB files
        run: make test
